### ISSUE TITLE
Fix mobile UI

### ISSUE THREAD

**Issue by magnobiet** [magnobiet/marvel-app#2]
Grid is broken.

This project is using the [Vuetify](https://vuetifyjs.com/).

| Home | List |
|---|---|
| ![image](https://user-images.githubusercontent.com/1743501/46365831-f7635b80-c64f-11e8-969e-338b9766123d.png) | ![image](https://user-images.githubusercontent.com/1743501/46366557-bc622780-c651-11e8-9083-a93e01577a3b.png) |

- [ ] Home
- [ ] List

**Comment by jkaan** [comment]
@magnobiet On what size were you making those screenshots?

What I'm seeing so far is that on Home it actually works correctly, only thing is that it does not work for the list.

**Comment by Deeadline** [comment]
![obraz](https://user-images.githubusercontent.com/26546280/46503597-92645d00-c82b-11e8-9f60-2dd399466057.png)

Do you accept something like this on Home menu ?

**Comment by Deeadline** [comment]
How about second image ? What do you expect ? Something like scroll your screen in x-axis and y-axis to see more ?

**Comment by magnobiet** [comment]
@Deeadline without horizontal scrolling, only vertical scrolling. Display 1 card (hero) per line.
