### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by magnobiet** [magnobiet/marvel-app#4]
Update project structure to Vue CLI 3.x (https://cli.vuejs.org/).

For other dependencies can use [`NCU`](https://github.com/tjunnone/npm-check-updates) package to verify this.

**Comment by jkaan** [comment]
@magnobiet I can take a look at this one.

**Comment by magnobiet** [comment]
> @magnobiet I can take a look at this one.

Sure, but the idea also is update project structure to Vue CLI 3.x. Ok? I believe that is a simple change.

**Comment by jkaan** [comment]
@magnobiet Okay cool. That should indeed not be too difficult.

**Comment by magnobiet** [comment]
Exactly @jkaan. Waiting your PR.

**Comment by Deeadline** [comment]
Hello, I will help you with this issue. 
Greetings you mate.

**Comment by jkaan** [comment]
@Deeadline As you're going to pick up this one I will pick up #2

**Comment by magnobiet** [comment]
> Hello, I will help you with this issue.
> Greetings you mate.

@Deeadline, your PR are welcome.
