### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by magnobiet** [magnobiet/marvel-app#8]
Create a Docker container including only `dist/` folder. As @oneturkmen suggests.

**Comment by magnobiet** [comment]
Now, API access is via the proxy route (http://localhost/api). In development mode, `PROXY_TARGET` is added to environment variables (https://github.com/magnobiet/marvel-app/blob/master/config/dev.env.js#L8). Same on the Heroku (https://github.com/magnobiet/marvel-app/blob/master/static.json#L9).

How to solve this on the container?

**Comment by gustafsilva** [comment]
I can help this task... :+1: 
Or will @oneturkman do that? :grimacing:

**Comment by magnobiet** [comment]
> I can help this task... +1
> Or will @oneturkman do that? grimacing

@gustafsilva I have another project that I have Docker in the plans. It is an application in PHP (Laravel). If you want to help, your PRs are welcome. https://github.com/magnobiet/laravel-bootstrap/issues/4

**Comment by gonzalesraul** [comment]
PR #9 submitted.

**Comment by oneturkmen** [comment]
Since @gonzalesraul, this issue can be closed (related to PR #9)
